import Head from "next/head";
import React, { useState } from "react";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Brands from "../components/Brands";
import Flashdeals from "../components/Flashdeals";
import NewProducts from "../components/NewProducts";
import Recommendations from "../components/Recommendations";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const THREE_DAYS_IN_MS = 24 * 60 * 60 * 1000;
  const CURRENT_DATE_IN_MS = new Date().getTime();
  const dateAfterThreeDays = CURRENT_DATE_IN_MS + THREE_DAYS_IN_MS;

  const [cartItems, setCartItems] = useState<any[]>([]);
  const addToCart = (product: any): any => {
    const chosenProd = cartItems.filter(
      (item: any) => item.id === product.id
    )[0];
    if (!chosenProd) {
      product["quantity"] = 1;
      setCartItems([...cartItems, product]);
    } else {
      const newCartItems = cartItems.map((itm) => {
        if (itm.id === product.id) {
          return { ...itm, quantity: (itm.quantity += 1) };
        }
        return itm;
      });
      setCartItems(newCartItems);
    }
  };

  const incrementQuantity = (product: any) => {
    const newc = cartItems.map((item) => {
      if (item.id === product.id) {
        return { ...item, quantity: (item.quantity += 1) };
      }
      return item;
    });
    setCartItems(newc);
  };

  const decrementQuantity = (product: any) => {
    let newc = cartItems.map((item) => {
      if (item.id === product.id) {
        return { ...item, quantity: (item.quantity -= 1) };
      }
      return item;
    });
    if (product.quantity === 0) {
      newc = cartItems.filter((item) => item.id !== product.id);
      setCartItems(newc);
    }
    setCartItems(newc);
  };

  return (
    <>
      <Head>
        <title>Universal Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main> */}
      <Header cart={cartItems.length} setCartItems={setCartItems} />
      <Navbar />
      <Hero />
      <Brands />
      <Flashdeals setCartItems={setCartItems} targetDate={dateAfterThreeDays} />
      <NewProducts />
      <Recommendations />
      <Footer />
      {/* </main> */}
    </>
  );
}

export default Home;
