import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/sign.module.scss";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Link from "next/link";
import { Button } from "primereact/button";
const inter = Inter({ subsets: ["latin"] });

function Signin() {
  const [loginDetails, setLoginDetails] = useState({
    email: "",
    password: "",
  });

  useEffect(() => {
    fetch("backend_api", {
      method: "POST",
      body: JSON.stringify(loginDetails),
      mode: "no-cors",
      redirect: "follow",
    })
      .then((result) => result.json())
      // get the user response(in this case token) from the backend and save to local storage to use
      .then((response) => {
        console.log("user", response);
        // set this item to the local storage for future usage
        localStorage.setItem("ecommerce_user", response);
      })
      .catch((err) => console.log("err", err));
  }, []);

  return (
    <>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <form className={styles.content}>
            <p className={styles.title}>Signin</p>
            <div className={styles.social}>
              <button className="btn">
                <i className="bi bi-facebook"></i>
              </button>
              <button className="btn">
                <i className="bi bi-twitter"></i>
              </button>
              <button className="btn">
                <i className="bi bi-google"></i>
              </button>
              <button className="btn">
                <i className="bi bi-linkedin"></i>
              </button>
            </div>

            <div className={styles.btninput}>
              <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">
                  <i className="bi bi-person-fill"></i>
                </span>
                <input
                  type="text"
                  className="form-control"
                  placeholder="Email"
                  aria-label="Email"
                  aria-describedby="basic-addon1"
                  onChange={(e) =>
                    setLoginDetails({ ...loginDetails, email: e.target.value })
                  }
                />
              </div>

              <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">
                  <i className="bi bi-lock-fill"></i>
                </span>
                <input
                  type="password"
                  className="form-control"
                  placeholder="Password"
                  aria-label="Password"
                  aria-describedby="basic-addon1"
                  onChange={(e) =>
                    setLoginDetails({
                      ...loginDetails,
                      password: e.target.value,
                    })
                  }
                />
              </div>
            </div>

            <div className={`${styles.submit}`}>
              <Button className="p-button-primary">Sign in</Button>
              <Button
                className="p-button-text"
                style={{ color: "var(--base-70)" }}
              >
                Forgot your password ?
              </Button>
            </div>

            <hr />
            <div className={styles.footer}>
              <span className="flex gap-3 align-items-center justify-content-end">
                Already have an account?{" "}
                <Link href="signup" className="">
                  Singn Up →
                </Link>{" "}
              </span>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}

export default Signin;
